![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [24]:
my_array = np.arange(10)
my_array [9:0:-2]

array([9, 7, 5, 3, 1])

In [3]:
import numpy as np

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [29]:
my_array [8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [36]:
my_array [2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [56]:
shape = (4,5)
ej4 = np.random.randint(1,20, size=(shape))
print(ej4)

ej5 = ej4 [::-1,::-1]
ej5

[[18 14  4 18 10]
 [12  3  5 18  9]
 [10 16  3  2  6]
 [12  4  7  7 12]]


array([[12,  7,  7,  4, 12],
       [ 6,  2,  3, 16, 10],
       [ 9, 18,  5,  3, 12],
       [10, 18,  4, 14, 18]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [60]:
ej5
print(ej5[:2,:2])

[[12  7]
 [ 6  2]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [62]:
ej5
print(ej5[:2,:3])

[[12  7  7]
 [ 6  2  3]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [66]:
ej5
print(ej5[:3,:5])

[[12  7  7  4 12]
 [ 6  2  3 16 10]
 [ 9 18  5  3 12]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [94]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x1= np.array([x[-2] + " " + x[0]])
x1

array(['Loro Loro'], dtype='<U9')

In [103]:
mask = (x == "Loro")
mask
x[mask]

array(['Loro', 'Loro'], dtype='<U5')

In [105]:
x= np.where (x=="Loro", "Loro", "")
x

array(['Loro', '', '', 'Loro', ''], dtype='<U4')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [88]:
ej9 = np.arange(21)
ej9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [113]:
ej5
print(ej5[:4,:5])

[[12  7  7  4 12]
 [ 6  2  3 16 10]
 [ 9 18  5  3 12]
 [10 18  4 14 18]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [117]:
ej11 = np.array([0,0,0,0,0,0,0,0,0,0])
ej11.itemsize
ej11[0]=2
ej11

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [121]:
ej12 = np.arange(10,50)
ej12 [::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [11]:
x = np.array([1,2,0,0,4,0])
y = np.nonzero(x)
print(y)

(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [126]:
shape = (10,10)
ej14 = np.random.randint(1,20, size=(shape))
print(ej14)
print(ej14.min())
print(ej14.max())

[[ 2 13 19  5  7 10  3 17 15 17]
 [16 14  9  3 15 11 11 19 17 15]
 [ 7  9 19  3 16  5 12 10  1  6]
 [ 5  2 15 17  6  2 15 15 17  2]
 [ 8 16  6 19 13  5 18  9 14  7]
 [ 5 19 12 14 15 10 12  2 11  2]
 [12 19  3  3 13 15 12 12 15 11]
 [ 3 16 13  4  9 12  5 15  5 19]
 [ 2 13  2  4  8  6 18 13  2 14]
 [11  8 10 11 11 14 18  3 11 19]]
1
19


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [132]:
shape = (30)
ej15 = np.random.randint(1,30, size=(shape))
ej15.mean()

13.366666666666667

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [20]:
ej16 = np.ones((8,8))
ej16[1:-1,1:-1] = 0
ej16

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [2]:
import numpy as np

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [124]:
ej17 = np.zeros ((8,8))
ej17 [1::2,0::2] = 1
ej17 [::2, 1::2] = 1
ej17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [127]:
np.tile(ej17,1)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [119]:
shape = (5,5)
ej15 = np.random.randint(1,30, size=(shape))
ej19 = ej15[0:5] - np.mean(ej19) / np.std(ej19)
ej19

array([[ 6.48807879, 20.48807879, 19.48807879, -0.51192121, 24.48807879],
       [12.48807879, 14.48807879, -0.51192121, -0.51192121, 21.48807879],
       [12.48807879, 13.48807879, 24.48807879,  7.48807879, 16.48807879],
       [ 9.48807879, 21.48807879, 19.48807879, 12.48807879,  0.48807879],
       [14.48807879,  7.48807879, 26.48807879, 19.48807879,  5.48807879]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [128]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
sequence = np.arange(11)
new_sequence = sequence.copy()
new_sequence[(sequence > 3) & (sequence < 8)] = -1
new_sequence

array([ 0,  1,  2,  3, -1, -1, -1, -1,  8,  9, 10])

In [131]:
negated_sequence = sequence.copy()
negated_sequence[(sequence > 3) & (sequence < 8)] *= -1
negated_sequence

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.